### ISSUE TITLE
Can't Make Person Records, Can't Delete Building Records

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#489]
Overnight 12/29-12/30.  I'm working on 1950, ED 14, Sheets 17-18.
    (1) I can't make person records, either in Batch or one-by-one using the Create button.
    (2) I can't delete building records.  Example: 402 Spring St Groton.  When I hit Edit, Delete, I am just returned to the undeleted record. I tried hitting Review first, then Delete, but that just brings back the unreviewed, undeleted record.
   
As I have been working this morning, I notice that some things are correcting themselves: the help text on edit screens of census records has reverted to "?" instead of "????"; the extra bolding on the person's name of the census record display has diminished.  So submitting this issue may be redundant.

**Comment by PatientRowan** [comment]
@EveSnyder

**Comment by PatientRowan** [comment]
Home page sometimes loads without the map image behind "Local History Starts With You."
Reloading fixes it.

<img width="1357" height="709" alt="Image" src="https://github.com/user-attachments/assets/d52f8b3c-c42c-498d-b893-7ab085af3897" />

**Comment by dfurber** [comment]
These issues should now be fixed. Please check and report back with new issues as well.

**Comment by PatientRowan** [comment]
I'm doing all the normal things this morning and they're working nicely as expected.

This is completely unimportant, but odd.  Sometimes the personal name at the top of a screen, as well as possible matches in the person record offerings, are bolded:

<img width="1160" height="442" alt="Image" src="https://github.com/user-attachments/assets/d01b438e-69bb-4dbf-8f6c-7116f5c0f974" />

After refreshing, they're back to normal:

<img width="1238" height="382" alt="Image" src="https://github.com/user-attachments/assets/95c948d1-a430-4cea-a010-7453b94fad75" />

**Comment by PatientRowan** [comment]
I don’t know if this is related to anything.  Maybe it’s nothing.  For at least a couple of months, I have noticed that the first time I click on Save to save a census record, it often doesn’t take the first time.  It’s happening often enough, and I’m alert enough about it, that I’m pretty sure it’s not just me being careless and going too fast.  Today I couldn’t get a record to save no matter how many times I clicked on it.  No error message.  It looked like all the other times I needed to click again, but more clicks did not work.
   I closed the window and started from scratch, with no further problems.
The record I couldn’t save was Sara Watrous, 1950, ED 14, Sheet 20, Line 29.

**Comment by dfurber** [comment]
Changes made, LMK.

**Comment by PatientRowan** [comment]
I thought I wouldn't complain about this as it's too trivial.  The drag-the-corner-to-enlarge-window doesn't work like it used to:

<img width="571" height="130" alt="Image" src="https://github.com/user-attachments/assets/88855e37-9fa7-4f2a-81e5-4cbed276b337" />

But I can live with it.
However, the adjustment you used to be able to make at the top of columns, to make the full text appear, also doesn't work, and I need it to do reviewing.
In this example, I want to drag the Industry column rightwards in order to reveal the full industry "Septic Tank Installation" without opening the census record.  but I can't grab the corner and drag.

<img width="654" height="281" alt="Image" src="https://github.com/user-attachments/assets/ad4fbf9f-2248-4518-8510-c4d0a4aefd33" />

**Comment by dfurber** [comment]
Should be fixed now.

**Comment by PatientRowan** [comment]
Slightly different in appearance now but fully functional, thank you.  I'll let you know about the save issue when I've done a sheet or two.

**Comment by PatientRowan** [comment]
We had a transcription session on Saturday for the 1870 census, so the system got a bit more of a stress test than I've been giving it alone.  Problems that I have been having, but not often, came up for others during the session.
    One pair got a duplicate notice, the one that says same name, same sheet &c.  @EveSnyder told them how to force the record into the system by introducing a typo in the name and then editing it.  I didn't see their work so I'm not sure what was going on, but in my experience recently, that duplicate notice is often spurious and simply means that the system did not advance the line number by 1.  Thus, it's not comparing the name against any other name, and the duplicate ED/Sheet/Line (in Groton 1950) or duplicate Sheet/Line (1870) is just a little glitch.  
     Two other pairs -- one including me, so I am sure that I saw this -- saved a record, reloaded the tab with the Sheet filter, and did not see the new record load in the list.  It took quite a lot of reloading for the record to show up.  I reassured the other pair that it would eventually appear and was relieved when that was true.
     In my pair, the person who was inputting, who is good, somehow got the system to save the same name, same sheet, same line--twice.

**Comment by PatientRowan** [comment]
I'm not sure this is worth troubling you about, but a volunteer has complained to us that there's too much white space in Source/Narratives now.  You can see it on any Source/Narrative but here is an example in between the funeral home link and the date 2022:

<img width="1130" height="647" alt="Image" src="https://github.com/user-attachments/assets/8ad40081-607a-494d-945c-6032d7c41041" />

**Comment by PatientRowan** [comment]
I was off inputting for a week because of the reviewing I had from the transcription session.  I only resumed transcribing on Sunday morning.  At that time, I still experienced the save button not taking.  I was also, again, thrown off the system.  I might have some more clues about when it happens: it's when I manually click on Create a New Person Record.  It's rare.  I get a message that I don't have permission to do that operation, and when I check, it's because I've been logged out.  I go back to my other open tabs, which still appear to have me logged in, but if I try to create a new person record again, I still get the no permission record.  The only thing to do is close all the tabs and log in properly.
I'm not reopening this issue until I've given it another day's workout.  Might not be today, but tomorrow for sure.
